name: Test Mobstac Awesome QR
 
on: [push]

jobs:
  test:
    name: Testing QR Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
      - name: Test Failure
        if: ${{ failure() }}
        shell: bash
        env:
          CHANNEL: 'engineering'
          TITLE: 'workflow-failed'
          REPOSITORY_NAME: 'mobstac-awesome-qr'
          RUN_ID: ${{ github.run_id }}
          ACTOR: ${{ github.actor }}
          COLOR: '#FF0000'
        run: |
          curl --request POST \
            --url https://hooks.slack.com/services/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 \
            --header 'Content-Type: application/json' \
            --header 'cache-control: no-cache' \
            --data "{\"channel\":\"${CHANNEL}\", \"attachments\": [ { \"title\":\"${TITLE} [ ${GITHUB_REF##*/} ] : [ ${ACTOR} ]\", \"text\": \"https://github.com/mobstac/${REPOSITORY_NAME}/actions/runs/${RUN_ID}\", \"color\": \"${COLOR}\" } ]}"
